# Generated by Django 4.0.5 on 2022-11-06 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0002_rename_user_msg_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='user_name',
            new_name='user',
        ),
    ]
